# Generated by Django 5.1.3 on 2024-11-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietpreference',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='dietpreference',
            name='preference',
        ),
        migrations.AddField(
            model_name='dietpreference',
            name='diet_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='vegetarian', max_length=10),
        ),
        migrations.CreateModel(
            name='WeeklyDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('meal', models.TextField()),
                ('recipe', models.TextField()),
                ('diet_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_diet', to='diet.dietpreference')),
            ],
        ),
    ]
