# Generated by Django 5.1.3 on 2024-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietpreference_user_alter_dietpreference_diet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklydietplan',
            name='diet_preference',
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='diet_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight')], default='gain', max_length=10),
        ),
    ]
