# Generated by Django 5.1.3 on 2024-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_remove_weeklydietplan_diet_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydietplan',
            name='Ingredient',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
