# Generated by Django 5.1.3 on 2024-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_weeklydietplan_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklydietplan',
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='weeklydietplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='weeklydietplan',
            name='recipe',
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='breakfast',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='breakfast_ingredients',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='breakfast_recipe',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='dinner',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='dinner_ingredients',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='dinner_recipe',
            field=models.TextField(default='To be added'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='lunch',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='lunch_ingredients',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='lunch_recipe',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='snacks',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='snacks_ingredients',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='weeklydietplan',
            name='snacks_recipe',
            field=models.TextField(default='Not specified'),
        ),
    ]
