# Generated by Django 5.1.3 on 2024-11-11 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmigraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmidata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmidata',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
