# Generated by Django 5.1.3 on 2024-11-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
