# Generated by Django 5.1.3 on 2024-11-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
                ('muscle_group', models.CharField(max_length=50)),
                ('cardio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('daily_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='user_dashboard.dailyexercise')),
            ],
        ),
    ]
