# Generated by Django 5.1.3 on 2024-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='daily_exercise',
        ),
        migrations.AddField(
            model_name='dailyexercise',
            name='exercises',
            field=models.ManyToManyField(related_name='daily_exercises', to='user_dashboard.exercise'),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='muscle_group',
            field=models.CharField(max_length=100),
        ),
    ]
